### ISSUE TITLE
Implemetation

### ISSUE THREAD

**Issue by jonathanong** [pillarjs/qs-strict#1]
From @fengmk2:

return `String` value
- if key not exists, return `undefined`
- `foo[bar][baz]=foobarbaz` => `{ 'foo[bar][baz]': 'foobarbaz' }`
  - `request.query.foo` return `undefined` 
  - `request.query['foo[bar][baz]']` return `'foobarbaz'`
- `a[]=b&a[]=c` => `{ 'a[]': 'b' }`
  - `request.query.a` return `undefined` 
  - `request.query['a[]']` return `b`
- `a=b&a=c` => `{ 'a': 'b' }`
  - `request.query.a` return `b`

**Comment by jonathanong** [comment]
right now it's more-or-less a copy and paste from io.js

**Comment by jonathanong** [comment]
> `a=b&a=c => { 'a': 'b' }`

right now i implemented it as last. why first vs. last? (i don't care)

how to stringify arrays and objects?
- `qs.stringify({ a: [1, 2] })` => `a=1,2` - what do you guys think?

**Comment by fengmk2** [comment]
if `qs.stringify({ a: ['1', '2'] })` => `a=1,2`, and `qs.parse('a=1,2')` => `{ a: ['1', '2'] }`? This result we don't want to.

How about we only impl `parse-strict` and ignore `stringify`?

**Comment by jonathanong** [comment]
ok!

**Comment by jonathanong** [comment]
done!

**Comment by fengmk2** [comment]
:+1:
